export type { BlendModeName, BurstPointConfig, EmissionConfig, ParticleModulesConfig, ParticleSystemConfig, SimulationSpace } from "./config/ParticleSystemConfig.js";
export type { IColorOverLifetimeModule } from "./contracts/IColorOverLifetimeModule.js";
export type { IColorProvider } from "./contracts/IColorProvider.js";
export type { BounceBoxConfig, BounceDampingConfig, BounceMode, BounceModuleConfig, IBounceModule } from "./contracts/IBounceModule.js";
export type { ICurveModule } from "./contracts/ICurveModule.js";
export type { IDirectionModule } from "./contracts/IDirectionModule.js";
export type { IEmitterModule } from "./contracts/IEmitterModule.js";
export type { IForceModule } from "./contracts/IForceModule.js";
export type { IParticleSystem, ParticleSystemFactory, ParticleSystemRenderer } from "./contracts/IParticleSystem.js";
export type { INumberProvider } from "./contracts/INumberProvider.js";
export type { IVelocityOverLifetimeModule } from "./contracts/IVelocityOverLifetimeModule.js";
export type { ISpeedOverLifetimeModule } from "./contracts/ISpeedOverLifetimeModule.js";
export type { ColorPoint, CurvePoint, DirectionVector, SpawnPosition } from "./types/CommonTypes.js";
export { ParticleSystem, type SerializedConfig, type SerializedConfigPatch } from "./system/ParticleSystem.js";
export { MultiParticleSystem } from "./system/MultiParticleSystem.js";
export { ParticlePool } from "./system/ParticlePool.js";
export { ConstantModule } from "./modules/value/ConstantModule.js";
export { RandomRangeModule } from "./modules/value/RandomRangeModule.js";
export { CurveModule } from "./modules/curve/CurveModule.js";
export { ConstantColorModule } from "./modules/color/ConstantColorModule.js";
export { RandomPickColorModule } from "./modules/color/RandomPickColorModule.js";
export { ColorGradientModule } from "./modules/color/ColorGradientModule.js";
export { DotEmitterModule } from "./modules/emitter/DotEmitterModule.js";
export { CircleEmitterModule } from "./modules/emitter/CircleEmitterModule.js";
export { BoxEmitterModule } from "./modules/emitter/BoxEmitterModule.js";
export { ConeDirectionModule } from "./modules/direction/ConeDirectionModule.js";
export { VectorCurveModule } from "./modules/velocity/VectorCurveModule.js";
export type { VectorCurveConfig } from "./modules/velocity/VectorCurveModule.js";
export { TurbulenceForceModule } from "./modules/force/TurbulenceForceModule.js";
export type { TurbulenceForceConfig } from "./modules/force/TurbulenceForceModule.js";
export { clamp, fract, hash2d, inverseLerp, lerp, smoothstep, valueNoise2d } from "./utils/math.js";
export { lerpColor, packColor, splitColor } from "./utils/color.js";
export { buildRuntimeConfigFromSerialized } from "./system/buildRuntimeConfigFromSerialized.js";
export type { IFlickeringOverLifetimeModule, FlickeringOverLifetimeState } from "./contracts/IFlickeringOverLifetimeModule.js";
export { FlickeringOverLifetimeModule } from "./modules/alpha/FlickeringOverLifetimeModule.js";
export type { FlickeringOverLifetimeConfig } from "./modules/alpha/FlickeringOverLifetimeModule.js";
export { SpeedOverLifetimeModule } from "./modules/velocity/SpeedOverLifetimeModule.js";
export { BounceModule } from "./modules/velocity/BounceModule.js";
export type { SpeedOverLifetimeConfig } from "./modules/velocity/SpeedOverLifetimeModule.js";
