import type { EditorConfig } from "./types";

export function createDefaultEditorConfig(): EditorConfig {
    return {
        name: "particle system",
        maxParticles: 3000,
        simulationSpace: "world",
        blendMode: "add",
        textureKind: "soft-circle",
        sequenceRandomStart: false,
        sequenceFrameRate: 12,
        emitterType: "box",
        emitterX: 0,
        emitterY: 0,
        emitterWidth: 80,
        emitterHeight: 16,
        emitterRadius: 24,
        emitterAlongShape: false,
        emitterRandomizePosition: 0,
        rate: 90,
        directionMin: -115,
        directionMax: -65,
        enablePrewarm: false,
        prewarm: 1,
        enableBurst: false,
        burst: 20,
        enableBurstByDemand: false,
        burstByDemand: 20,
        enableDurationLoop: false,
        duration: 3,
        loop: true,
        enableTimelineBursts: false,
        timelineBursts: [
            { time: 0.35, count: 60 },
            { time: 1.25, count: 90 },
            { time: 2.2, count: 120 },
        ],
        lifetimeMode: "min-max",
        lifetimeConst: 1.2,
        lifetimeMin: 0.9,
        lifetimeMax: 1.8,
        enableStartSpeed: true,
        enableSpeedOverLifetime: false,
        speedCurve: [
            { t: 0, value: 120, randomOffset: 0 },
            { t: 1, value: 0, randomOffset: 0 },
        ],
        speedOverLifetimeFade: true,
        startSpeedMode: "min-max",
        speedConst: 120,
        speedMin: 90,
        speedMax: 220,
        enableStartRotation: false,
        startRotationMode: "min-max",
        rotationConst: 0,
        rotationMin: 0,
        rotationMax: 6.283185307179586,
        enableAngularVelocity: false,
        angularVelocityMode: "min-max",
        angularVelocityConst: 0,
        angularVelocityMin: -5,
        angularVelocityMax: 5,
        angleKeepDirection: false,
        enableStartSize: true,
        startSizeMode: "min-max",
        sizeConst: 0.5,
        sizeMin: 0.1,
        sizeMax: 0.3,
        enableStartAlpha: false,
        startAlphaMode: "constant",
        alphaConst: 1,
        alphaMin: 0.6,
        alphaMax: 1,
        enableStartColor: true,
        startColors: ["#FFCC66", "#FF8A4C", "#FFE8A3"],
        enableBounce: false,
        bounceMode: "screen",
        bounceBoxX: 0,
        bounceBoxY: 0,
        bounceBoxWidth: 800,
        bounceBoxHeight: 600,
        bounceDampingMin: 0,
        bounceDampingMax: 0,
        enableSizeOverLifetime: true,
        sizeCurve: [
            { t: 0, value: 0.15 },
            { t: 0.12, value: 1 },
            { t: 0.75, value: 0.85 },
            { t: 1, value: 0 },
        ],
        enableAlphaOverLifetime: true,
        alphaCurve: [
            { t: 0, value: 0 },
            { t: 0.08, value: 1 },
            { t: 0.8, value: 1 },
            { t: 1, value: 0 },
        ],
        enableScaleXYOverLifetime: false,
        scaleXCurve: [
            { t: 0, value: 1 },
            { t: 1, value: 1 },
        ],
        scaleYCurve: [
            { t: 0, value: 1 },
            { t: 1, value: 1 },
        ],
        enableFlickeringOverLifetime: false,
        flickeringGap: 0.2,
        flickeringMin: 0,
        flickeringMax: 1,
        flickeringRandomGapOffset: 0,
        flickeringRandomMinMaxOffset: 0,
        flickeringFade: false,
        flickeringStartTime: 0,
        flickeringEndTime: 1,
        enableColorOverLifetime: false,
        colorCurve: [
            { t: 0, color: "#FFF5BD" },
            { t: 0.45, color: "#FF9A2F" },
            { t: 1, color: "#3B1700" },
        ],
        enableVelocityOverLifetime: false,
        velocityXCurve: [
            { t: 0, value: 0 },
            { t: 0.5, value: 0 },
            { t: 1, value: 0 },
        ],
        velocityYCurve: [
            { t: 0, value: 0 },
            { t: 0.45, value: -10 },
            { t: 1, value: 20 },
        ],
        enableGravity: true,
        gravity: 90,
        enableForce: false,
        forceAmplitudeX: 30,
        forceAmplitudeY: 18,
        forceSpatialScale: 0.01,
        forceTimeScale: 0.8,
        forceSeed: 7,
    };
}
