import type { BlendModeName, CurvePoint } from "pixi-particle";

export type NumberMode = "constant" | "min-max";
export type EmitterType = "dot" | "circle" | "box";
export type TextureKind = "circle" | "soft-circle" | "square" | "diamond" | "star";
export type BounceMode = "screen" | "box";

export type ColorKeyPoint = {
    t: number;
    color: string;
};

export type TimelineBurstPoint = {
    time: number;
    count: number;
};

export type EditorConfig = {
    name: string;
    maxParticles: number;
    simulationSpace: "world" | "local";
    blendMode: BlendModeName;
    textureKind: TextureKind;
    sequenceRandomStart: boolean;
    sequenceFrameRate: number;
    emitterType: EmitterType;
    emitterX: number;
    emitterY: number;
    emitterWidth: number;
    emitterHeight: number;
    emitterRadius: number;
    emitterAlongShape: boolean;
    emitterRandomizePosition: number;
    rate: number;
    directionMin: number;
    directionMax: number;
    enablePrewarm: boolean;
    prewarm: number;
    enableBurst: boolean;
    burst: number;
    enableBurstByDemand: boolean;
    burstByDemand: number;
    enableDurationLoop: boolean;
    duration: number;
    loop: boolean;
    enableTimelineBursts: boolean;
    timelineBursts: TimelineBurstPoint[];
    lifetimeMode: NumberMode;
    lifetimeConst: number;
    lifetimeMin: number;
    lifetimeMax: number;
    enableStartSpeed: boolean;
    enableSpeedOverLifetime: boolean;
    speedCurve: CurvePoint[];
    speedOverLifetimeFade: boolean;
    startSpeedMode: NumberMode;
    speedConst: number;
    speedMin: number;
    speedMax: number;
    enableStartRotation: boolean;
    startRotationMode: NumberMode;
    rotationConst: number;
    rotationMin: number;
    rotationMax: number;
    enableAngularVelocity: boolean;
    angularVelocityMode: NumberMode;
    angularVelocityConst: number;
    angularVelocityMin: number;
    angularVelocityMax: number;
    angleKeepDirection: boolean;
    enableStartSize: boolean;
    startSizeMode: NumberMode;
    sizeConst: number;
    sizeMin: number;
    sizeMax: number;
    enableStartAlpha: boolean;
    startAlphaMode: NumberMode;
    alphaConst: number;
    alphaMin: number;
    alphaMax: number;
    enableStartColor: boolean;
    startColors: string[];
    enableBounce: boolean;
    bounceMode: BounceMode;
    bounceBoxX: number;
    bounceBoxY: number;
    bounceBoxWidth: number;
    bounceBoxHeight: number;
    bounceDampingMin: number;
    bounceDampingMax: number;
    enableSizeOverLifetime: boolean;
    sizeCurve: CurvePoint[];
    enableAlphaOverLifetime: boolean;
    alphaCurve: CurvePoint[];
    enableScaleXYOverLifetime: boolean;
    scaleXCurve: CurvePoint[];
    scaleYCurve: CurvePoint[];
    enableFlickeringOverLifetime: boolean;
    flickeringGap: number;
    flickeringMin: number;
    flickeringMax: number;
    flickeringRandomGapOffset: number;
    flickeringRandomMinMaxOffset: number;
    flickeringFade: boolean;
    flickeringStartTime: number;
    flickeringEndTime: number;
    enableColorOverLifetime: boolean;
    colorCurve: ColorKeyPoint[];
    enableVelocityOverLifetime: boolean;
    velocityXCurve: CurvePoint[];
    velocityYCurve: CurvePoint[];
    enableGravity: boolean;
    gravity: number;
    enableForce: boolean;
    forceAmplitudeX: number;
    forceAmplitudeY: number;
    forceSpatialScale: number;
    forceTimeScale: number;
    forceSeed: number;
};
